spring:
  application:
    name: eureka-client-ad-dump
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ad-data?autoReconnect=true
    username: root
    password: 12345
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2